### PR TITLE
Add example for getStaticPaths

### PR DESCRIPTION
**Pull request by stewartmcgown**

### CODE REVIEW

**Comment by chaddjohnson** [comment]
Nice work. This works great for my static site. I think this should be merged in.

**Comment by pacxiu** [comment]
@stewartmcgown 

Hey there, I tried to utilize your script, however on running that in Vercel I got following error:
image

Did you maybe enocunter that?

**Comment by stewartmcgown** [comment]
Vercel doesnt use the server path, they use serverless. I'll add it to the docs!

**Comment by tobiastornros** [comment]
Also dynamic routes, for example **[id]** should be added in the **ignoredPaths** list.

**Comment by stewartmcgown** [comment]
> Also dynamic routes, for example **[id]** should be added in the **ignoredPaths** list.

Yep, that was already in the change. If it's not clear we can make it something more explicit?

**Pull request merged**
