### PR TITLE
improve ignoredPaths filtering (support filtering exportPathMap paths, match filter against full path)

### PR DESCRIPTION
**Pull request by gavinsharp**
I ran into two issues with the current `ignoredPaths` filtering:
- it doesn't apply to pages from `exportPathMap`:  the filtering is only applied in `buildPathMap`, which gets called before `exportPathMap` adds paths
- because it is applied during directory traversal, the `ignoredPaths` are only matched against filenames, rather than the full path. This can make it hard to filter pages more specifically.
  - example: if you have a URL structure like:
    ```
    /pageA
    /subdir/pageA
    /subdir/pageB
    ```
     and you only want to exclude `/subdir/pageA`, the existing filtering mechanism doesn't let you. You either have to filter on `pageA` or `subdir`, and both will filter out the two matching paths.

This PR addresses those by making two changes:
1. refactor to move the filtering logic to after `exportPathMap` is called
  - I had to modify the snapshots for a couple of tests (45aa58a440fb00c07060208a9c5eaed6fec5c621) because they were testing the `buildPathMap` output specifically (which now doesn't apply filtering)
1. because the filtering logic is now applied later, it is now applied to the full path, rather than just filenames at each level of the path. This means that you can add e.g. `subdir/pageA` (from example above) to `ignoredPaths` to filter out only that specific page.

There is a chance that this second behaviour change affects the output for existing users, but I think that should only be the case if their existing `ignoredPath` does not match any paths (because this is loosening the filtering criteria). I think it should probably be fine to make this change with release notes, but it might merit a major version bump?

### CODE REVIEW

**Comment by IlusionDev** [comment]
Bot - We're going to review the pull when we have time

**Comment by gavinsharp** [comment]
By the way - I also plan to open a PR for another feature request I wanted: https://github.com/GoProperly/nextjs-sitemap-generator/pull/2

**Comment by IlusionDev** [comment]
You right with make a release notes with all changes explained.
I'm sure that someone will be affected with these changes in the filter criteria.
And thank you a lot with these changes. I don't have much time to make improvements and refactors to the library

**Comment by IlusionDev** [comment]
Tomorrow I will make the release notes and a new version to publish

**Pull request merged**
